import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
    carCard: {
        width: 200,
        height: 140,
        marginRight: 15,
        backgroundColor: theme.colors.card,
        position: 'relative',
        overflow: 'hidden',
    },
    carImage: {
        width: '100%',
        height: '100%',
    },
    carOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 10,
        paddingTop: 40,
    },
    carDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
    },
    carName: {
        fontFamily: theme.fonts.primary.bold,
        fontSize: 16,
        color: theme.colors.white,
    },
    specsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    carSpecsText: {
        fontFamily: theme.fonts.secondary.regular,
        fontSize: 10,
        color: theme.colors.secondary,
    },
    tuneButton: {
        marginLeft: 6,
        padding: 4,
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 4,
    },
    statsContainer: {
        marginTop: 4,
        height: 4,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 2,
        overflow: 'hidden',
        width: '100%',
    },
    statsBar: {
        height: '100%',
        backgroundColor: theme.colors.primary,
    },
    respectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.1)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    respectCount: {
        color: theme.colors.white,
        fontFamily: theme.fonts.secondary.bold,
        fontSize: 12,
        marginLeft: 4,
    },
    showcaseMode: {
        borderWidth: 2,
        borderColor: '#00F0FF',
        shadowColor: '#00F0FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
        elevation: 10,
    },
    showcaseOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 240, 255, 0.1)',
        zIndex: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    showcaseText: {
        color: '#00F0FF',
        fontFamily: theme.fonts.primary.bold,
        fontSize: 14,
        letterSpacing: 2,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    showcaseButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'rgba(0, 240, 255, 0.2)',
        padding: 5,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#00F0FF',
        zIndex: 10,
    },
});
